[tools]
node = "23.11.1"
"npm:@google/gemini-cli" = "latest"
"npm:cz-git" = "latest"
"npm:czg" = "latest"
pnpm = "latest"
usage = "latest"

[settings]
experimental = true
idiomatic_version_file_enable_tools = ["node"]
